In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())


1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [4]:
# 3. Create a null vector of size 10 
array = np.array([0,0,0,0,0,0,0,0,0,0])
np.size(array)



10

In [5]:
array_a = np.zeros(10)

In [6]:
array_a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
type(array_a)

numpy.ndarray

In [14]:
# 4 How to find the memory size of any array
memory = array.itemsize
print(f"memory size of this array is: ", memory )

memory size of this array is:  4


In [15]:
# 5. How to get the documentation of the numpy add function from the command line? 
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [16]:
# 6. Create a null vector of size 10 but the fifth value which is 1 
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
# 7. Create a vector with values ranging from 10 to 49
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
# 8. Reverse a vector (first element becomes last)
reversed = array[::-1]
reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [22]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero = np.nonzero([1,2,0,0,4,0])
non_zero

(array([0, 1, 4], dtype=int64),)

In [26]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# 12. Create a 3x3x3 array with random values 
np.random.rand(3,3,3)

array([[[0.39687859, 0.8676685 , 0.8849644 ],
        [0.30732077, 0.15777573, 0.64258341],
        [0.47587329, 0.59914994, 0.49786627]],

       [[0.95277203, 0.72855562, 0.83078296],
        [0.06439577, 0.11446831, 0.81103507],
        [0.20881416, 0.17679779, 0.6783448 ]],

       [[0.84660231, 0.41277479, 0.65865547],
        [0.21161586, 0.22319998, 0.42479337],
        [0.48504172, 0.48838102, 0.82249036]]])

In [28]:
## 13. Create a 10x10 array with random values and find the minimum and maximum values
np.random.rand(10,10)

array([[0.48937497, 0.95090553, 0.35234685, 0.18104521, 0.86990702,
        0.25045664, 0.17611207, 0.29736951, 0.29884399, 0.9522336 ],
       [0.12079798, 0.34385251, 0.22476964, 0.88457582, 0.90183914,
        0.21389222, 0.29359917, 0.65973529, 0.39231364, 0.21588416],
       [0.52899124, 0.40272252, 0.52557615, 0.30305021, 0.8583537 ,
        0.25230766, 0.64446556, 0.04896726, 0.75668848, 0.58365789],
       [0.03125199, 0.77400079, 0.27738834, 0.53009361, 0.12589149,
        0.66425111, 0.15176575, 0.53027709, 0.3520815 , 0.73441843],
       [0.09372393, 0.52778289, 0.00667939, 0.95889309, 0.11208977,
        0.80748084, 0.71782924, 0.22654377, 0.63459596, 0.11624706],
       [0.32298736, 0.62822229, 0.65956667, 0.99349233, 0.31690153,
        0.34017239, 0.40385248, 0.37229014, 0.77482963, 0.50954945],
       [0.73798294, 0.6539723 , 0.56194455, 0.4828787 , 0.79547992,
        0.42159558, 0.92725066, 0.08271773, 0.04383024, 0.86223461],
       [0.23267266, 0.95218268, 0.1441116