In [4]:
import numpy as np

In [5]:
print(np.__version__)
print(np.show_config())


1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [6]:
# 3. Create a null vector of size 10 
array = np.array([0,0,0,0,0,0,0,0,0,0])
np.size(array)



10

In [7]:
array_a = np.zeros(10)

In [8]:
array_a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
type(array_a)

numpy.ndarray

In [10]:
# 4 How to find the memory size of any array
memory = array.itemsize
print(f"memory size of this array is: ", memory )

memory size of this array is:  4


In [11]:
# 5. How to get the documentation of the numpy add function from the command line? 
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [12]:
# 6. Create a null vector of size 10 but the fifth value which is 1 
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
# 7. Create a vector with values ranging from 10 to 49
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
# 8. Reverse a vector (first element becomes last)
reversed = array[::-1]
reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [15]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero = np.nonzero([1,2,0,0,4,0])
non_zero

(array([0, 1, 4], dtype=int64),)

In [17]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# 12. Create a 3x3x3 array with random values 
np.random.rand(3,3,3)

array([[[0.71214998, 0.30323648, 0.22514184],
        [0.48081761, 0.12913512, 0.37950354],
        [0.80273288, 0.18961564, 0.88299695]],

       [[0.04947555, 0.32945415, 0.76400411],
        [0.87161668, 0.03019582, 0.81283346],
        [0.54652317, 0.66667792, 0.8494702 ]],

       [[0.32459247, 0.75446324, 0.18171821],
        [0.95140299, 0.03833364, 0.36959115],
        [0.3514307 , 0.77429719, 0.26784482]]])

In [25]:
## 13. Create a 10x10 array with random values and find the minimum and maximum values
rand_array = np.random.rand(10,10)
print(rand_array)

print(np.amin(rand_array))
print(np.amax(rand_array))

[[0.25687605 0.95123628 0.76811409 0.75146661 0.30304266 0.8894099
  0.05215258 0.54758279 0.90484919 0.44197262]
 [0.5532397  0.87089482 0.02882577 0.10488105 0.71057408 0.26078546
  0.41705953 0.28171883 0.72553781 0.47610128]
 [0.02510473 0.05249715 0.70608902 0.56996277 0.1726378  0.27959796
  0.50902825 0.52846169 0.53228684 0.60291107]
 [0.66511466 0.82538169 0.03731797 0.64185794 0.31768458 0.29918352
  0.38209665 0.36871649 0.51289104 0.66835059]
 [0.47634139 0.75518994 0.15400085 0.82140371 0.81210759 0.82995319
  0.91845545 0.69649155 0.32576897 0.47030298]
 [0.63216102 0.36823021 0.35857707 0.99125634 0.68146988 0.76727755
  0.91414342 0.89395453 0.66423587 0.34290475]
 [0.54032299 0.0732377  0.66526822 0.32324198 0.25359974 0.97672122
  0.38307685 0.56470233 0.71012053 0.1223871 ]
 [0.9733357  0.5668821  0.33353014 0.78108591 0.05952896 0.73821283
  0.54490284 0.14516924 0.57419053 0.86256193]
 [0.71958332 0.9414686  0.47455009 0.56532233 0.23610912 0.8038887
  0.76865284 0

In [84]:
rand_array_int = np.random.randint(1,100,(3,3,3))
print(rand_array_int)
print(np.amin(rand_array_int))
print(np.amax(rand_array_int))

[[[29  6 18]
  [19  1 78]
  [11 50 20]]

 [[43 43 55]
  [76 77 75]
  [44 52 63]]

 [[37 66  2]
  [ 3 26 61]
  [25 14 25]]]
1
78


In [30]:
# 15. Create a 2d array with 1 on the border and 0 inside

array_with_zero = np.ones((7, 7), dtype = int)
array_with_zero[1:-1, 1:-1] = 0
print(array_with_zero)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [32]:
# 16 How to add a border (filled with 0's) around an existing array?
np.pad(array_with_zero,1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.pad(array_with_zero,2)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.pad(array_with_zero,(2,3))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 17. What is the result of the following expression?
'''python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
'''

In [38]:
0 * np.nan

nan

In [39]:
np.nan == np.nan

False

In [40]:
np.inf > np.nan

#inf 無限大

False

In [41]:
np.nan - np.nan

nan

In [43]:
np.nan in set([np.nan])

True

In [45]:
0.3 == 3*0.1

False

In [55]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag([1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [85]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
c_array = np.zeros((8,8), dtype = int)
c_array

c_array[::2,1::2] = 1 # 0行目から行方向に2個ごと、1列目から2個ごと
print(c_array)

#c_array[::1,::1] = 0
#print(c_array)
#        zeile,spalte
c_array[1::2,::2] = 1 #　1行目から行方向に2個ごと、0列目から二個ごと
print(c_array)



[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [88]:
c_array_second = np.zeros((8,8),dtype = int)
c_array_second[::2,::2] = 1
print(c_array_second)
c_array_second[1::2, 1::2] = 1
print(c_array_second)


[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [89]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
array = np.unravel_index(99,(6,7,8))
array

(1, 5, 3)