In [18]:
import numpy as np


In [19]:
# 21. Create a checkerboard 8x8 matrix using the tile function
a = np.array([[1,0],[0,1]])

np.tile(a, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [22]:
# 22. Normalize a 5x5 random matrix
b = np.random.random((5,5))
print(b)
b = (b-np.mean(b)/np.std(b))
print(b)
fd

[[0.16382095 0.17624645 0.66111166 0.14995282 0.64344015]
 [0.5969248  0.72076737 0.98052511 0.66707133 0.05927956]
 [0.70915081 0.15778548 0.05072712 0.20893481 0.00809108]
 [0.02984709 0.40297058 0.04118047 0.81976063 0.07335433]
 [0.29453328 0.62991072 0.71378292 0.23821156 0.09598101]]
[[-1.07861613 -1.06619063 -0.58132542 -1.09248425 -0.59899693]
 [-0.64551228 -0.52166971 -0.26191197 -0.57536574 -1.18315752]
 [-0.53328626 -1.08465159 -1.19170995 -1.03350226 -1.234346  ]
 [-1.21258999 -0.8394665  -1.2012566  -0.42267645 -1.16908274]
 [-0.9479038  -0.61252635 -0.52865416 -1.00422552 -1.14645607]]


In [23]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte,1), ('a', np.ubyte, 1)])
color

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1133091599.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte,1), ('a', np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [24]:
np.dtype(color)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [29]:
np.size(color)

1

In [28]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
c = np.ones((5,3))
d = np.ones((3,2))
e = np.dot(c,d)
e

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [30]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
c = np.ones((5,3))
d = np.ones((3,2))
e = np.matmul(c,d)
e

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [31]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. 
f = np.arange(11)
f[(3 < f) & ( f <= 8)] *= -1
print(f)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [32]:
#### 26. What is the output of the following script? (★☆☆)
'''python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
'''

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#

9
10


In [34]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
'''python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''

4

In [ ]:

3**3
2 << 3 >> 2

In [35]:

#### 28. What are the result of the following expressions? (★☆☆)
'''
python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
'''

np.array(0) / np.array(0)

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1364160288.py:9: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [36]:
np.array(0) // np.array(0)

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [37]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [47]:
#### 29. How to round away from zero a float array ? (★☆☆)

Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ 7.31734039 -5.51286307  3.08221792  9.44320766  6.16377032  6.68251673
  7.71737879 -3.47499335 -7.444716   -9.02107482]
[  8.  -6.   4.  10.   7.   7.   8.  -4.  -8. -10.]


In [43]:
#### 30. How to find common values between two arrays? (★☆☆)

h = np.random.randint(0,10,5)
print(h)
i = np.random.randint(0,10,5)
print(i)
j = np.intersect1d(h,i)
print(j)

[2 4 1 2 2]
[5 4 6 6 8]
[4]
