In [65]:
import numpy as np
from sklearn import preprocessing


ModuleNotFoundError: No module named 'sklearn'

In [19]:
# 21. Create a checkerboard 8x8 matrix using the tile function
a = np.array([[1,0],[0,1]])

np.tile(a, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [22]:
# 22. Normalize a 5x5 random matrix
b = np.random.random((5,5))
print(b)
b = (b-np.mean(b)/np.std(b))
print(b)
fd

[[0.16382095 0.17624645 0.66111166 0.14995282 0.64344015]
 [0.5969248  0.72076737 0.98052511 0.66707133 0.05927956]
 [0.70915081 0.15778548 0.05072712 0.20893481 0.00809108]
 [0.02984709 0.40297058 0.04118047 0.81976063 0.07335433]
 [0.29453328 0.62991072 0.71378292 0.23821156 0.09598101]]
[[-1.07861613 -1.06619063 -0.58132542 -1.09248425 -0.59899693]
 [-0.64551228 -0.52166971 -0.26191197 -0.57536574 -1.18315752]
 [-0.53328626 -1.08465159 -1.19170995 -1.03350226 -1.234346  ]
 [-1.21258999 -0.8394665  -1.2012566  -0.42267645 -1.16908274]
 [-0.9479038  -0.61252635 -0.52865416 -1.00422552 -1.14645607]]


In [23]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte,1), ('a', np.ubyte, 1)])
color

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1133091599.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte,1), ('a', np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [24]:
np.dtype(color)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [29]:
np.size(color)

1

In [28]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
c = np.ones((5,3))
d = np.ones((3,2))
e = np.dot(c,d)
e

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [30]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
c = np.ones((5,3))
d = np.ones((3,2))
e = np.matmul(c,d)
e

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [31]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. 
f = np.arange(11)
f[(3 < f) & ( f <= 8)] *= -1
print(f)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [32]:
#### 26. What is the output of the following script? (★☆☆)
'''python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
'''

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#

9
10


In [34]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

# ?????
'''python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''

4

In [ ]:

3**3
2 << 3 >> 2

In [35]:

#### 28. What are the result of the following expressions? (★☆☆)
'''
python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
'''

np.array(0) / np.array(0)

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1364160288.py:9: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [36]:
np.array(0) // np.array(0)

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [37]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [47]:
#### 29. How to round away from zero a float array ? (★☆☆)

Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ 7.31734039 -5.51286307  3.08221792  9.44320766  6.16377032  6.68251673
  7.71737879 -3.47499335 -7.444716   -9.02107482]
[  8.  -6.   4.  10.   7.   7.   8.  -4.  -8. -10.]


In [43]:
#### 30. How to find common values between two arrays? (★☆☆)

h = np.random.randint(0,10,5)
print(h)
i = np.random.randint(0,10,5)
print(i)
j = np.intersect1d(h,i)
print(j)

[2 4 1 2 2]
[5 4 6 6 8]
[4]


In [48]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [51]:
#### 32. Is the following expressions true? (★☆☆)

print(np.sqrt(-1) == np.emath.sqrt(-1))

print(np.sqrt(-1) == np.emath.sqrt(-1))


False
False


C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1050454388.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1050454388.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


In [53]:
#### 33. How to get the dates of yesterday, today and tomorrow? 
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"Yesterday is :", yesterday )
print(f"Today is :", today )
print(f"Tomorrow is :", tomorrow )

Yesterday is : 2022-11-29
Today is : 2022-11-30
Tomorrow is : 2022-12-01


In [58]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
import numpy as np
date_of_July_16 = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(date_of_July_16)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [60]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

# at frist (A+B), and then (-A/2). answer of (A+B) mutplyed by answer of (-A/2)
print(((2+3)*(-2/2)) )

-5.0


In [64]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
j = np.random.uniform(1, 10, 10)
print(j)

print(j - j%1)
print(j // 1)
print(np.floor(j))
print(j.astype(int))
print(np.trunc(j))

[3.34749657 5.04196541 7.50112332 4.43680813 7.16030389 1.99151955
 2.46594496 1.87152816 3.53773587 6.83794478]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]
[3 5 7 4 7 1 2 1 3 6]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]


In [2]:
from sklearn import preprocessing

In [ ]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [ ]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [ ]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [ ]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
