In [5]:
import numpy as np
from sklearn import preprocessing


In [3]:
# 21. Create a checkerboard 8x8 matrix using the tile function
a = np.array([[1,0],[0,1]])

np.tile(a, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [4]:
# 22. Normalize a 5x5 random matrix
b = np.random.random((5,5))
print(b)
b = (b-np.mean(b)/np.std(b))
print(b)
fd

[[0.95639648 0.9724699  0.49989909 0.22705312 0.25598911]
 [0.11666139 0.27959483 0.88690368 0.7932186  0.40335187]
 [0.23275983 0.61085921 0.72771403 0.51716566 0.00493055]
 [0.97212047 0.63751843 0.85602617 0.64738343 0.53041917]
 [0.86550186 0.59423947 0.1289216  0.31672281 0.62919873]]
[[-0.94999153 -0.93391811 -1.40648892 -1.67933489 -1.65039891]
 [-1.78972663 -1.62679319 -1.01948433 -1.11316941 -1.50303614]
 [-1.67362819 -1.2955288  -1.17867398 -1.38922235 -1.90145746]
 [-0.93426754 -1.26886959 -1.05036184 -1.25900459 -1.37596884]
 [-1.04088615 -1.31214854 -1.77746642 -1.5896652  -1.27718929]]


NameError: name 'fd' is not defined

In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte,1), ('a', np.ubyte, 1)])
color

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1133091599.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte,1), ('a', np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [ ]:
np.dtype(color)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [ ]:
np.size(color)

1

In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
c = np.ones((5,3))
d = np.ones((3,2))
e = np.dot(c,d)
e

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
c = np.ones((5,3))
d = np.ones((3,2))
e = np.matmul(c,d)
e

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. 
f = np.arange(11)
f[(3 < f) & ( f <= 8)] *= -1
print(f)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
#### 26. What is the output of the following script? (★☆☆)
'''python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
'''

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#

9
10


In [ ]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

# ?????
'''python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''

4

In [ ]:

3**3
2 << 3 >> 2

In [ ]:

#### 28. What are the result of the following expressions? (★☆☆)
'''
python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
'''

np.array(0) / np.array(0)

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1364160288.py:9: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

C:\Users\satom\AppData\Local\Temp\ipykernel_19348\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [ ]:
#### 29. How to round away from zero a float array ? (★☆☆)

Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ 7.31734039 -5.51286307  3.08221792  9.44320766  6.16377032  6.68251673
  7.71737879 -3.47499335 -7.444716   -9.02107482]
[  8.  -6.   4.  10.   7.   7.   8.  -4.  -8. -10.]


In [ ]:
#### 30. How to find common values between two arrays? (★☆☆)

h = np.random.randint(0,10,5)
print(h)
i = np.random.randint(0,10,5)
print(i)
j = np.intersect1d(h,i)
print(j)

[2 4 1 2 2]
[5 4 6 6 8]
[4]


In [ ]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [ ]:
#### 32. Is the following expressions true? (★☆☆)

print(np.sqrt(-1) == np.emath.sqrt(-1))

print(np.sqrt(-1) == np.emath.sqrt(-1))


False
False


C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1050454388.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
C:\Users\satom\AppData\Local\Temp\ipykernel_19348\1050454388.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


In [ ]:
#### 33. How to get the dates of yesterday, today and tomorrow? 
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"Yesterday is :", yesterday )
print(f"Today is :", today )
print(f"Tomorrow is :", tomorrow )

Yesterday is : 2022-11-29
Today is : 2022-11-30
Tomorrow is : 2022-12-01


In [ ]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
import numpy as np
date_of_July_16 = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(date_of_July_16)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

# at frist (A+B), and then (-A/2). answer of (A+B) mutplyed by answer of (-A/2)
print(((2+3)*(-2/2)) )

-5.0


In [ ]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
j = np.random.uniform(1, 10, 10)
print(j)

print(j - j%1)
print(j // 1)
print(np.floor(j))
print(j.astype(int))
print(np.trunc(j))

[3.34749657 5.04196541 7.50112332 4.43680813 7.16030389 1.99151955
 2.46594496 1.87152816 3.53773587 6.83794478]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]
[3 5 7 4 7 1 2 1 3 6]
[3. 5. 7. 4. 7. 1. 2. 1. 3. 6.]


In [ ]:
from sklearn import preprocessing

In [13]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
l = np.zeros((5,5))
print(l)
l += np.arange(5)


print(l)
k = np.arange(0,5).reshape(5,5)
k



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


ValueError: cannot reshape array of size 5 into shape (5,5)

In [ ]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [ ]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [16]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
o = np.random.random(10)
o.sort(ascending = False)
print(o)

TypeError: 'ascending' is an invalid keyword argument for sort()